---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot2-0618
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot2-0618 
  name: chatbot2-0618
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi